import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pythonSidebar: [{type: 'autogenerated', dirName: 'school/python'}],
  agenticFrameworksSidebar: [{type: 'autogenerated', dirName: 'school/agentic-frameworks'}],
  appSecuritySidebar: [{type: 'autogenerated', dirName: 'school/app-security'}],
  cicdPipelinesSidebar: [{type: 'autogenerated', dirName: 'school/cicd-pipelines'}],
  fastapiConceptsSidebar: [{type: 'autogenerated', dirName: 'school/fastapi-concepts'}],
  gitWorkflowsSidebar: [{type: 'autogenerated', dirName: 'school/git-workflows'}],
  incidentManagementSidebar: [{type: 'autogenerated', dirName: 'school/incident-management'}],
  observabilitySidebar: [{type: 'autogenerated', dirName: 'school/observability'}],
  oopPatternsSidebar: [{type: 'autogenerated', dirName: 'school/oop-patterns'}],
  releaseDeploymentSidebar: [{type: 'autogenerated', dirName: 'school/release-deployment'}],
  requirementsEstimationSidebar: [{type: 'autogenerated', dirName: 'school/requirements-estimation'}],
  sdlcAgileSidebar: [{type: 'autogenerated', dirName: 'school/sdlc-agile'}],
  sliSloSidebar: [{type: 'autogenerated', dirName: 'school/sli-slo'}],
  softwareTestingSidebar: [{type: 'autogenerated', dirName: 'school/software-testing'}],
  teamStructureSidebar: [{type: 'autogenerated', dirName: 'school/team-structure'}],
};

export default sidebars;
