from pathlib import Path

root = Path(r"d:\Projects\playbook\docs\school\python")

files = [
    'intro/what-is-python.mdx',
    'intro/setup-python.mdx',
    'intro/python-execution-flow.mdx',
    'intro/first-python-program.mdx',
    'fundamentals/variables.mdx',
    'fundamentals/data-types.mdx',
    'fundamentals/operators.mdx',
    'fundamentals/input-output.mdx',
    'fundamentals/type-conversion.mdx',
    'fundamentals/comments-docstrings.mdx',
    'control-flow/if-else.mdx',
    'control-flow/nested-conditions.mdx',
    'control-flow/loops.mdx',
    'control-flow/break-continue-pass.mdx',
    'control-flow/pattern-programs.mdx',
    'control-flow/match-case.mdx',
    'functions/functions-basics.mdx',
    'functions/arguments-parameters.mdx',
    'functions/return-values.mdx',
    'functions/lambda-functions.mdx',
    'functions/recursion.mdx',
    'functions/decorators.mdx',
    'functions/generators.mdx',
    'functions/iterators.mdx',
    'functions/closures.mdx',
    'collections/lists.mdx',
    'collections/tuples.mdx',
    'collections/sets.mdx',
    'collections/dictionaries.mdx',
    'collections/list-comprehension.mdx',
    'collections/dictionary-comprehension.mdx',
    'collections/collections-module.mdx',
    'collections/deque.mdx',
    'collections/counter.mdx',
    'collections/defaultdict.mdx',
    'strings/string-basics.mdx',
    'strings/string-methods.mdx',
    'strings/string-formatting.mdx',
    'strings/regex.mdx',
    'strings/unicode.mdx',
    'strings/f-strings.mdx',
    'oops/classes-objects.mdx',
    'oops/constructors.mdx',
    'oops/inheritance.mdx',
    'oops/polymorphism.mdx',
    'oops/encapsulation.mdx',
    'oops/abstraction.mdx',
    'oops/magic-methods.mdx',
    'oops/dataclasses.mdx',
    'oops/solid-principles.mdx',
    'oops/composition-vs-inheritance.mdx',
    'error-handling/exceptions.mdx',
    'error-handling/custom-exceptions.mdx',
    'error-handling/logging.mdx',
    'error-handling/debugging.mdx',
    'error-handling/production-debugging.mdx',
    'file-handling/reading-files.mdx',
    'file-handling/writing-files.mdx',
    'file-handling/csv-files.mdx',
    'file-handling/json-files.mdx',
    'file-handling/pathlib.mdx',
    'file-handling/file-best-practices.mdx',
    'modules-packages/modules.mdx',
    'modules-packages/packages.mdx',
    'modules-packages/virtual-environments.mdx',
    'modules-packages/pip.mdx',
    'modules-packages/pyproject-toml.mdx',
    'modules-packages/dependency-management.mdx',
    'advanced-python/memory-management.mdx',
    'advanced-python/garbage-collection.mdx',
    'advanced-python/shallow-vs-deep-copy.mdx',
    'advanced-python/mutability.mdx',
    'advanced-python/context-managers.mdx',
    'advanced-python/descriptors.mdx',
    'advanced-python/metaclasses.mdx',
    'advanced-python/monkey-patching.mdx',
    'advanced-python/dynamic-typing.mdx',
    'advanced-python/python-internals.mdx',
    'concurrency/threading.mdx',
    'concurrency/multiprocessing.mdx',
    'concurrency/asyncio.mdx',
    'concurrency/async-await.mdx',
    'concurrency/race-conditions.mdx',
    'concurrency/queues.mdx',
    'concurrency/locks-semaphores.mdx',
    'concurrency/gil.mdx',
    'api-development/requests-library.mdx',
    'api-development/rest-api-basics.mdx',
    'api-development/fastapi.mdx',
    'api-development/flask.mdx',
    'api-development/authentication.mdx',
    'api-development/middleware.mdx',
    'api-development/api-versioning.mdx',
    'api-development/rate-limiting.mdx',
    'databases/sqlite.mdx',
    'databases/postgresql.mdx',
    'databases/sqlalchemy.mdx',
    'databases/orm-vs-raw-sql.mdx',
    'databases/transactions.mdx',
    'databases/indexing.mdx',
    'databases/connection-pooling.mdx',
    'testing/pytest.mdx',
    'testing/unit-testing.mdx',
    'testing/mocking.mdx',
    'testing/integration-testing.mdx',
    'testing/load-testing.mdx',
    'testing/test-best-practices.mdx',
    'performance/profiling.mdx',
    'performance/memory-optimization.mdx',
    'performance/caching.mdx',
    'performance/lazy-loading.mdx',
    'performance/vectorization.mdx',
    'performance/numpy-performance.mdx',
    'performance/performance-best-practices.mdx',
    'system-design/python-architecture.mdx',
    'system-design/scalable-python.mdx',
    'system-design/event-driven-systems.mdx',
    'system-design/queue-systems.mdx',
    'system-design/distributed-systems.mdx',
    'system-design/microservices.mdx',
    'system-design/production-patterns.mdx',
    'ai-engineering/python-for-ai.mdx',
    'ai-engineering/numpy.mdx',
    'ai-engineering/pandas.mdx',
    'ai-engineering/llm-basics.mdx',
    'ai-engineering/rag-pipelines.mdx',
    'ai-engineering/vector-databases.mdx',
    'ai-engineering/ai-agents.mdx',
    'ai-engineering/async-ai-workflows.mdx',
    'ai-engineering/ai-observability.mdx',
    'interview-prep/top-python-interview-questions.mdx',
    'interview-prep/tricky-python-questions.mdx',
    'interview-prep/debugging-rounds.mdx',
    'interview-prep/coding-round-patterns.mdx',
    'interview-prep/system-design-rounds.mdx',
    'interview-prep/senior-python-questions.mdx',
    'best-practices/clean-code.mdx',
    'best-practices/project-structure.mdx',
    'best-practices/coding-standards.mdx',
    'best-practices/security-best-practices.mdx',
    'best-practices/production-checklists.mdx',
    'best-practices/scalability-guidelines.mdx',
    'best-practices/engineering-principles.mdx',
]

root.mkdir(parents=True, exist_ok=True)

all_dirs = {root}
for file in files:
    path = root / file
    path.parent.mkdir(parents=True, exist_ok=True)
    all_dirs.add(path.parent)
    if not path.exists():
        title = path.stem.replace('-', ' ').title()
        content = f"---\nsidebar_position: 1\n---\n\n# {title}\n\nPlaceholder: introduce {title}.\n"
        path.write_text(content, encoding='utf-8')

for d in all_dirs:
    cat_path = d / '_category_.json'
    if not cat_path.exists():
        label = 'Python' if d == root else d.name.replace('-', ' ').title()
        json_text = '{"label": "' + label + '", "collapsed": false}'
        cat_path.write_text(json_text, encoding='utf-8')
